file_format: "1"
id: "ballpadyl"
name: "ballpadyl"
type: shield
url: https://github.com/ThisIsVamp/zmk-config-ballpadylrev1
requires: [nice_nano_v2]
features:
  - keys
siblings:
  - ballpadyl_left
  - ballpadyl_right
