file_format: "1"
id: ballpadyl
name: ballpadyl
type: shield
url: https://github.com/kata0510/ballpadyl
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
  - studio
siblings:
  - ballpadyl_left
  - ballpadyl_right
